git:
  overrideGpg: true

gui:
  theme:
    activeBorderColor:
      - "#fdd017"
      - bold
    inactiveBorderColor:
      - "#0f7db1"
    selectedLineBgColor:
      - "#21283b"
    defaultFgColor:
      - "#ffffff"
