return {}
-- return {
-- 	"akinsho/bufferline.nvim",
-- 	dependencies = { "nvim-tree/nvim-web-devicons" },
-- 	version = "*",
-- 	opts = {
-- 		options = {
-- 			offset = {
-- 				{
-- 					filetype = "NvimTree",
-- 					text = "File Explorer",
-- 					highlight = "Directory",
-- 					text_align = "center",
-- 				},
-- 			},
-- 			mode = "tabs",
-- 			diagnostics = "nvim_lsp",
-- 			numbers = function(opts)
-- 				return string.format("%s|%s", opts.id, opts.raise(opts.ordinal))
-- 			end,
-- 		},
-- 	},
-- }
